### PR TITLE
linting cleanup and fix for new lsp-mode refactor

### PR DESCRIPTION
**Pull request by seanfarley**
This is mainly a cleanup for the lisp code but also fixes issue #5

### CODE REVIEW

**Comment by andrew-christianson** [comment]
thanks!  I'll review and merge tonight

**Comment by seanfarley** [comment]
There are still a few open questions, by the way:

* I needed to remove `'pyls` from `lsp-clients` to have this module "work out of the box." I don't know the implications of removing it, though.

* Do we actually want to keep the old way of adding `lsp-mode` around? It causes a linting error (not a big deal) but I'm unsure it's possible to use that code path anymore.

Thoughts on either?

**Comment by cpbotha** [comment]
@seanfarley the new lsp-mode docs state that built-in language servers get priority -1, and external ones by default 0, so they should take precedence.

According to that, it should not be necessary to remove 'pyls from lsp-clients.

@andrew-christianson Would be great to see this merged!

**Comment by seanfarley** [comment]
Sorry for the late reply, been on holiday travel. Hmm, I didn't realize the priority is set automatically. I'll test that tonight!

**Comment by seanfarley** [comment]
Seems like the priority now works, so yay!

**Comment by seanfarley** [comment]
Any word @andrew-christianson on merging this?

**Comment by andrew-christianson** [comment]
@seanfarley thanks for the ping, I'd missed this over the holidays.  Looks great!

**Pull request merged**
