### PR TITLE
Replace defvars by defcustoms

### PR DESCRIPTION
**Pull request by seblemaguer**
Meant to solve #23

### CODE REVIEW

**Comment by seagle0128** [comment]
I think the changes should be updated.

**Comment by seblemaguer** [comment]
hello,

done, it should be fine now.

**Comment by dakra** [comment]
You should also specify a `:type` and since you have a `defgroup` you don't need to specify `:group` as `defcustom` automatically takes the last defined group.

**Comment by seagle0128** [comment]
I agree with @dakra . `:type` is necessary for `defgroup`.

**Comment by seblemaguer** [comment]
I added the type (I was not aware of such a thing but it is quite convenient :D)

for `lsp-python-ms-extra-paths` I repeated directory but I didn't if you wanted to support files as well.

**Pull request merged**
