### PR TITLE
Remove toplevel sexp and wrap it with *-initialize function

### PR DESCRIPTION
**Pull request by conao3**
Hi.
First, very thank you for develop/maintain such a many and
greatest lsp packages.

As I found this package is not confirm Elisp convention, I fix it.

The convention is below statement.
[Emacs Lisp Coding Conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html)
```
Simply loading a package should not change Emacs's editing
behavior. Include a command or commands to enable and disable the
feature, or to invoke it.

This convention is mandatory for any file that includes custom
definitions. If fixing such a file to follow this convention
requires an incompatible change, go ahead and make the
incompatible change; don't postpone it.
```

So, I remove toplevel sexps and wrap them with *-initialize funciton.
It's true this PR break users init.el, but this is needed for
confirm Elisp coding convention.
(The user actions required by this change can be found by
referring to the changes in the README.)

### CODE REVIEW

**Comment by seagle0128** [comment]
After consideration for a several days, I decide to merge this PR. Thanks for the contribution!

**Comment by conao3** [comment]
Thanks! I am convinced of following the elisp convention will benefit users in the long run.

**Comment by seagle0128** [comment]
@conao3 It was too quick to say that. Sorry for reverting it. I have to do that since I got some feedback it will confuse the users. All other client packages (e.g. `lsp-clients`, `ccls`, `lsp-java`, etc.) using old method `(require xxx)` to register the clients. We'd better keep that way unless we decide to move all clients to the new methods.

**Comment by conao3** [comment]
Confusion is natural. But I thought you were understanding of future health more than the pain of it.
For example, `flycheck` can add functionality by installing other packages as well as `lsp`, but these packages are implemented as I suggested.

Top3 flycheck packages from [MELPA](https://melpa.org/#/?q=flycheck&sort=downloads&asc=false)
- [flycheck-package](https://github.com/purcell/flycheck-package) initialize with `(flycheck-package-setup)`
- [flycheck-rust](https://github.com/flycheck/flycheck-rust) initialize with `(flycheck-rust-setup)`
- [flycheck-haskell](https://github.com/flycheck/flycheck-haskell) initialize with `(flycheck-haskell-setup)`

**Comment by seagle0128** [comment]
I know it's a better behavior. But should change form lsp core `lsp-clients`. And I don't think it's easy. 

cc @yyoncho thoughts?

**Pull request merged**
