### PR TITLE
fix wrong usage of encode-time

### PR DESCRIPTION
**Pull request by kiennq**
Correct the usage of `encode-time`, will make the download of `python-language-server-ms` success.
The currently used syntax is only available in [Emacs 27](https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS)

### CODE REVIEW

**Comment by yyoncho** [comment]
@seagle0128 can you take a look?

**Comment by seagle0128** [comment]
I am fine with the change. I noticed @isolet reported #39.

@isolet, can you please test it?

**Comment by smallzhan** [comment]
@seagle0128 @yyoncho According to my test in both Emacs26 & 27, this PR solves #39.

**Comment by seagle0128** [comment]
Thank you, @smallzhan .
@yyoncho , Please merge.

**Comment by failable** [comment]
Still can't get it work

    Command "/Users/isol/.emacs.d/savefile/var/lsp-python-ms/Microsoft.Python.LanguageServer" is not present on the path.
    Command "pyls" is present on the path.
    Found the following clients for /Users/isol/Git/tags.py: (server-id pyls, priority -1)
    The following clients were selected based on priority: (server-id pyls, priority -1)

But the executable is in fact there.

**Comment by failable** [comment]
The extracted server has no executable flag.

    -rw-r--r--   1 isol staff 163K Jun 21 12:02 Microsoft.Python.LanguageServer


I wonder if it's only the issue of my OS.

**Comment by seagle0128** [comment]
@isolet Did you set `lsp-python-ms-dir` or `lsp-python-ms-executable`?
"/Users/isol/.emacs.d/savefile/var/lsp-python-ms/Microsoft.Python.LanguageServer" is not the default path. `lsp-python-ms-dir` and `lsp-python-ms-executable` shoud be matched. If the path is invalid, the `chmod` may not be executed correctly. You can try to run `chmod +x` manually.

**Comment by failable** [comment]
I only set `lsp-python-ms-dir`. `lsp-python-ms-dir` and `lsp-python-ms-executable` do match. I have to `chmod +x` manually.

**Comment by seagle0128** [comment]
@isolet I set `lsp-python-dir` to `~/.emacs.d/var/lsp-python-ms/` and did test with Emacs 27 on macOS. It does work well. Please update to the latest version and retry.

**Pull request merged**
